### ISSUE TITLE
m_dPktSndPeriod - "unhealthy" rounding

### ISSUE THREAD

**Issue by caracostea** [dump247/udt-net#23]
Inside CCCWrapper::setPacketSendPeriod, when setting the native m_dPktSndPeriod to the TimeStamp value, since value.Ticks is of type long, doing m_dPktSndPeriod = (double)(value.Ticks / 10); trims valuable decimals BEFORE converting to double. Instead, I suggest doing m_dPktSndPeriod = value.Ticks / 10.0;

Even though such a small resolution of time would not mean much for the packet sending rate, if the fine increase/decrease of the rate is done for every ack or loss based on the prior value of PacketSendPeriod (which actually makes sense), precisely those decimals will make the difference.

**Comment by dump247** [comment]
For reference, here is the line in question: https://github.com/dump247/udt-net/blob/master/UdtProtocol/CCCWrapper.cpp#L147
