### ISSUE TITLE
Udt Net on Visual studio 2015

### ISSUE THREAD

**Issue by DanKyungu** [dump247/udt-net#29]
Hi,I try to compile an generate a UdtNet DLL for .NET 4.5 and I get errors how can I do if I want to resolve the problems and if I want to use native udt library in unmanaged code in C# how can do it,Thanks for your help

**Comment by dump247** [comment]
Please provide some details on what issue you are experiencing. How did you setup the project? Specifically, what errors are you getting? I don't understand what you mean by "use native udt library in unmanaged code in C#." Do you mean you have some unmanaged/native code and you want to manipulate the udt socket?

**Comment by DanKyungu** [comment]
If possible can you publish the .NET wrapper of UDT in visual C++ 2015 or higher,an other problem is i want to export the UDT API to a C# DLL by using __declspec,thanks for your help
