### ISSUE TITLE
Needs help on TcpClient and TcpListener

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dump247/udt-net#9]
```
As mentioned in ToDo list "Something similar to TcpClient and TcpListener", are 
you working on this ? If yes when can we expect it ? 
```

Original issue reported on code.google.com by `ppdevm...@gmail.com` on 27 Nov 2012 at 4:25

**Comment by dump247** [comment]
I haven't done any real work on the project for a few years, so it is not likely this will ever be implemented. Closing the issue.
